# Generated by Django 4.1.13 on 2025-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_create_comment_model'),
    ]

    operations = [
    ]
