# Generated by Django 4.1.13 on 2025-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250619_1921'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_created_0e6ed4_idx',
            old_name='blog_comment_created_idx',
        ),
    ]
